### ISSUE TITLE
Cannot find -lz.a

### ISSUE THREAD

**Issue by theodelrieu** [hoxnox/conan-zlib#1]
Hello, there seems to be a bug in the `conanfile.py` in the `do_package_info` method. (version 1.2.11)

When trying to configure `sqlcipher`, the following error is raised:

`/usr/bin/ld: cannot find -lz.a
Completely removing the `if...else` at line 39 fixes the problem for me.

Did I overlook something that would explain why this line is necessary?

**Comment by hoxnox** [comment]
Hello, can you provide more information: OS, compiler, how you configure sqlcipher, so I could reproduce the problem?

The reason for `if..else` block - is to specify what library version to use - shared or static.

**Comment by theodelrieu** [comment]
I'm on Debian 8/sid, with GCC 7.

To reproduce, I build zlib 1.2.11, OpenSSL 1.0.2l with zlib activated, then sqlcipher 3.4.1.

I get a misleading error message:

> configure: error: C compiler cannot create executables
> See `config.log' for more details

And in the `config.log`:

> configure:2853: checking whether the C compiler works
> configure:2875: gcc -m64 -s -fPIC -I/home/theo/.conan/data/OpenSSL/1.0.2l/test/test/package/d5ea31a589673c83bb2cad43a650805ff8c60596/include -I/home/theo/.conan/data/zlib/1.2.11/test/test/package/3f81c8eee37294bf41a90a28a9f912f01829220b/include -DNDEBUG -D_GLIBCXX_USE_CXX11_ABI=1 -DSQLITE_HAS_CODEC -DSQLCIPHER_CRYPTO_OPENSSL -m64 -L/home/theo/.conan/data/OpenSSL/1.0.2l/test/test/package/d5ea31a589673c83bb2cad43a650805ff8c60596/lib -L/home/theo/.conan/data/zlib/1.2.11/test/test/package/3f81c8eee37294bf41a90a28a9f912f01829220b/lib conftest.c -lssl -lcrypto -ldl -lz.a -ldl >&5
> /usr/bin/ld: cannot find -lz.a

I still don't get why it is useful to explicitely mark `z.a` in the `package_info` method.
Since there is only one version (static or shared) in the final package, `-lz` would not be ambiguous.

That's the only change I had to do to make it work.

**Comment by hoxnox** [comment]
> Since there is only one version (static or shared) in the final package

Unfortunately it is not. Both static and shared versions of the library can be in the "lib" directory of the package. There might be two solutions: 1). Explicitly remove (not copy) unapropriate version in package method 2). Explicitly mark z.a in package_info method.
I've chosen second. I don't understand why it doesn't work in your case. Sorry. May be the problem in openssl package...
